# Generated by Django 4.2.7 on 2023-11-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.CharField(max_length=255)),
                ('msg', models.TextField()),
                ('user', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='roomid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('user1', models.CharField(max_length=255)),
                ('user2', models.CharField(max_length=255)),
            ],
        ),
    ]
